{
  imports = [
    ./audio.nix
    ./boot.nix
    ./clamav-scanner.nix
    ./display-manager.nix
    ./env.nix
    ./firewall.nix
    ./hardware.nix
    ./home-manager.nix
    ./kernel.nix
    ./nh.nix
    ./nix.nix
    ./nvf.nix
    ./programming-languages.nix
    ./qemu.nix
    ./ssh.nix
    ./timezone.nix
    ./user.nix
  ];
}
