{
  imports = [
    ./audio.nix
    ./boot.nix
    ./clamav-scanner.nix
    ./display-manager.nix
    ./env.nix
    ./firewall.nix
    ./gamemode.nix
    ./hardware.nix
    ./home-manager.nix
    ./hyprland.nix
    ./kernel.nix
    ./llm.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./services.nix
    ./steam.nix
    ./syncthing.nix
    ./timezone.nix
    ./user.nix
    ./virt-manager.nix
    ./virtualization.nix
    ./vpn.nix
  ];
}
