{
  imports = [
    ./boot.nix
    ./display-manager.nix
    ./env.nix
    ./firewall.nix
    ./hardware.nix
    ./home-manager.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./nvf.nix
    ./rustdesk-server.nix
    ./ssh.nix
    ./sops.nix
    ./store-management.nix
    ./timezone.nix
    ./user.nix
    ./virtualization.nix
  ];
}
