# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

    boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = 
      { device = "/dev/disk/by-uuid/c84d908b-518b-49e3-a5bf-9940915aa9ab";
        fsType = "btrfs";
      };

    swapDevices = 
      [ { device = "/dev/disk/by-uuid/63d2cf4c-45de-4538-90c4-e333a7c21a5d"; }
      ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
