# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

    boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = 
      { device = "/dev/disk/by-uuid/ace06a67-ce43-4eb7-9d65-d522770d8b76";
        fsType = "btrfs";
      };

    swapDevices = 
      [ { device = "/dev/disk/by-uuid/2812155d-5a9c-4916-84fd-30e5618a74cf"; }
      ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
