{
  imports = [
    ./bat.nix
    ./btop-rocm.nix
    ./cursor.nix
    ./dconf.nix
    ./eza.nix
    ./fastfetch.nix
    ./fish.nix
    ./fonts.nix
    ./ghostty.nix
    ./git.nix
    ./hyprland
    ./keepassxc.nix
    ./librewolf.nix
    ./oh-my-posh.nix
    ./ranger.nix
    ./swaync
    ./tmux.nix
    ./waybar
    ./wofi
    ./zathura.nix
    ./zed-editor.nix
  ];
}
